In [2]:
import requests

In [3]:
with open("secrets.txt","r") as f:
    string = f.read()

IHRE_KENNUNG = string.split('\n')[1]
IHR_PASSWORT = string.split('\n')[3]

In [10]:
url = f'https://www-genesis.destatis.de/genesisWS/rest/2020/data/resultfile?username={IHRE_KENNUNG}&password={IHR_PASSWORT}&name=digitalisation&area=user&compress=false&format=csv&language=en'
res = requests.get(url)

In [2]:
import pandas as pd
from io import StringIO

In [4]:
pd.read_excel('digitalisation.xlsx')

/home/mabioo/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,"IKT-Indikatoren für Unternehmen: Deutschland, Jahre,\nWirtschaftszweige, Beschäftigtengrößenklassen",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255,Unnamed: 256,Unnamed: 257,Unnamed: 258,Unnamed: 259
0,Nutzung v.Informations-u.Kommunikationstech.i....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deutschland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IKT-Indikatoren für Unternehmen (Prozent),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jahr\nWZ2008 (Abschnitte): IKT\n,NaN,NaN,Nutzung von IKT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Computer,Beschäftigung eigener IT-Fachkräfte (ab 10 Bes...,Beschäftigung eigener IT-Fachkräfte (alle Unte...,Interne/externe IT-Fortbildungen (ab 10 Besch.),Interne/externe IT-Fortbildungen (alle Untern.),Fortbildungen für IT-Fachkräfte (ab 10 Besch.),Fortbildungen für IT-Fachkräfte (alle Unterneh...,...,Schwierigk. b.Verkauf in EU-Staaten: MwSt-System,Verkäufe über EDI,Umsatz über EDI,"Verkäufe über EDI, Inland","Verkäufe über EDI, andere EU-Staaten","Verkäufe über EDI, übrige Staaten","Einkäufe über eine Website, App oder über EDI",Tätige Personen mit Computernutzung,Tätige Personen mit Internetzugang,Tätige Personen mit mobilem Internetzugang
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,NaN,NaN,50-249 Beschäftigte,-,-,-,-,-,-,-,...,-,-,0,-,-,-,-,-,94,/
396,NaN,NaN,250 und mehr Beschäftigte,-,-,-,-,-,-,-,...,-,-,0,-,-,-,-,-,0,0
397,______________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,"© Statistisches Bundesamt (Destatis), 2023 | S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
string_repr = res.content.decode()
string_repr = string_repr[string_repr.find('ICT indicators for enterprises (percent)'):]
# string_repr
# with open('test.csv', 'w') as f:
#     f.write(string_repr)

In [13]:
l = StringIO(string_repr)
pd.read_csv(l, delimiter=";")

,ICT indicators for enterprises (percent),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255,Unnamed: 256,Unnamed: 257,Unnamed: 258,Unnamed: 259
0,NaN,NaN,NaN,Use of ICT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Computers,Employment of own IT specialists (10 or more p...,Employment of own IT specialists (all enterpri...,Internal/external IT training (10 or more p.e.),Internal/external IT training (all enterprises),Training for IT specialists (10 or more p.e.),Training for IT specialists (all enterprises),...,Diffic. with sales to EU countries: VAT system,Sales via EDI,EDI turnover,"EDI-type sales, own country","EDI-type sales, other EU countries","EDI-type sales, rest of the world","Purchases via website, app or EDI",Persons employed who use a computer,Persons employed with internet access,Persons employed with mobile internet access
2,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,WZ08-C,Manufacturing,1 to 9 persons employed,93,-,-,-,-,-,-,...,-,/,/,-,-,-,43,-,49,19
4,NaN,NaN,10 to 49 persons employed,99,12,-,21,-,6,-,...,-,11,31,-,-,-,52,-,36,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,NaN,NaN,50 to 249 persons employed,-,-,-,-,-,-,-,...,-,-,0,-,-,-,-,-,94,/
393,NaN,NaN,250 or more persons employed,-,-,-,-,-,-,-,...,-,-,0,-,-,-,-,-,0,0
394,__________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,"© Federal Statistical Office, Wiesbaden 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,created: 2023-01-26 / 14:36:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
import requests

url = "https://apidojo-yahoo-finance-v1.p.rapidapi.com/auto-complete"

querystring = {"q":"tesla","region":"US"}

headers = {
	"X-RapidAPI-Key": "36ec980bcbmshe700420eefee90ap1601c7jsn750ce5280f1f",
	"X-RapidAPI-Host": "apidojo-yahoo-finance-v1.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{"message":"You are not subscribed to this API."}